<a href="https://colab.research.google.com/github/RoshanKumar854/ML-Projects/blob/main/Go_Daddy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
train_df = pd.read_csv("train.csv")
train_df = train_df.dropna()

In [4]:
type(train_df["first_day_of_month"])

pandas.core.series.Series

In [5]:
# current date minus a year
from datetime import datetime
from dateutil.relativedelta import relativedelta

In [6]:
train_df['Day Month'] = train_df["first_day_of_month"].str[4:]
train_df['Year'] = train_df["first_day_of_month"].str[:4]

In [7]:
type(train_df['Year'])

pandas.core.series.Series

In [8]:
type(train_df['Year'])

pandas.core.series.Series

In [9]:
train_df['Year'] = pd.to_numeric(train_df['Year'])
train_df['Year'] = train_df['Year'] - 2

In [10]:
train_df['Year']

0         2017
1         2017
2         2017
3         2017
4         2017
          ...
101666    2020
101667    2020
101668    2020
101669    2020
101670    2020
Name: Year, Length: 101671, dtype: int64

In [11]:
train_df['Month'] = train_df["first_day_of_month"].str[5:7]

In [12]:
train_df['Month']
train_df['Month'] = pd.to_numeric(train_df['Month'])

In [13]:
train_df['Month'].value_counts()

8     10428
9     10427
10    10427
11     7821
12     7821
1      7821
2      7821
3      7821
4      7821
5      7821
6      7821
7      7821
Name: Month, dtype: int64

In [14]:
train_df

,row_id,cfips,county,state,first_day_of_month,microbusiness_density,active,Day Month,Year,Month
0,1001_2019-08-01,1001,Autauga County,Alabama,2019-08-01,3.007682,1249.0,-08-01,2017,8
1,1001_2019-09-01,1001,Autauga County,Alabama,2019-09-01,2.884870,1198.0,-09-01,2017,9
2,1001_2019-10-01,1001,Autauga County,Alabama,2019-10-01,3.055843,1269.0,-10-01,2017,10
3,1001_2019-11-01,1001,Autauga County,Alabama,2019-11-01,2.993233,1243.0,-11-01,2017,11
4,1001_2019-12-01,1001,Autauga County,Alabama,2019-12-01,2.993233,1243.0,-12-01,2017,12
...,...,...,...,...,...,...,...,...,...,...
101666,48175_2022-04-01,48175,Goliad County,Texas,2022-04-01,1.691226,101.0,-04-01,2020,4
101667,48175_2022-05-01,48175,Goliad County,Texas,2022-05-01,1.674481,100.0,-05-01,2020,5
101668,48175_2022-06-01,48175,Goliad County,Texas,2022-06-01,1.657736,99.0,-06-01,2020,6
101669,48175_2022-07-01,48175,Goliad County,Texas,2022-07-01,1.657736,99.0,-07-01,2020,7
101670,48175_2022-08-01,48175,Goliad County,Texas,2022-08-01,1.674481,100.0,-08-01,2020,8

In [15]:
censor_df = pd.read_csv("census_starter.csv")
censor_df

,pct_bb_2017,pct_bb_2018,pct_bb_2019,pct_bb_2020,pct_bb_2021,cfips,pct_college_2017,pct_college_2018,pct_college_2019,pct_college_2020,...,pct_it_workers_2017,pct_it_workers_2018,pct_it_workers_2019,pct_it_workers_2020,pct_it_workers_2021,median_hh_inc_2017,median_hh_inc_2018,median_hh_inc_2019,median_hh_inc_2020,median_hh_inc_2021
0,76.6,78.9,80.6,82.7,85.5,1001,14.5,15.9,16.1,16.7,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
1,74.5,78.1,81.8,85.1,87.9,1003,20.4,20.7,21.0,20.2,...,1.4,1.3,1.4,1.0,1.3,52562,55962.0,58320,61756.0,64346.0
2,57.2,60.4,60.5,64.6,64.6,1005,7.6,7.8,7.6,7.3,...,0.5,0.3,0.8,1.1,0.8,33368,34186.0,32525,34990.0,36422.0
3,62.0,66.1,69.2,76.1,74.6,1007,8.1,7.6,6.5,7.4,...,1.2,1.4,1.6,1.7,2.1,43404,45340.0,47542,51721.0,54277.0
4,65.8,68.5,73.0,79.6,81.0,1009,8.7,8.1,8.6,8.9,...,1.3,1.4,0.9,1.1,0.9,47412,48695.0,49358,48922.0,52830.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,82.2,82.4,84.0,86.7,88.4,56037,15.3,15.2,14.8,13.7,...,0.6,0.6,1.0,0.9,1.0,71083,73008.0,74843,73384.0,76668.0
3138,83.5,85.9,87.1,89.1,90.5,56039,37.7,37.8,38.9,37.2,...,0.7,1.2,1.4,1.5,2.0,80049,83831.0,84678,87053.0,94498.0
3139,83.8,88.2,89.5,91.4,90.6,56041,11.9,10.5,11.1,12.6,...,1.2,1.2,1.4,1.7,0.9,54672,58235.0,63403,72458.0,75106.0
3140,76.4,78.3,78.2,82.8,85.4,56043,15.4,15.0,15.4,15.0,...,1.3,1.0,0.9,0.9,1.1,51362,53426.0,54158,57306.0,62271.0
3141,71.1,73.3,76.8,79.7,81.3,56045,14.1,13.5,13.4,12.7,...,0.6,0.6,0.0,0.0,0.0,59605,52867.0,57031,53333.0,65566.0

In [20]:
train_df = pd.merge(train_df, censor_df, on='cfips', how="inner")

In [21]:
train_df

,row_id,cfips,county,state,first_day_of_month,microbusiness_density,active,Day Month,Year,Month,...,pct_it_workers_2017_y,pct_it_workers_2018_y,pct_it_workers_2019_y,pct_it_workers_2020_y,pct_it_workers_2021_y,median_hh_inc_2017_y,median_hh_inc_2018_y,median_hh_inc_2019_y,median_hh_inc_2020_y,median_hh_inc_2021_y
0,1001_2019-08-01,1001,Autauga County,Alabama,2019-08-01,3.007682,1249.0,-08-01,2017,8,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
1,1001_2019-09-01,1001,Autauga County,Alabama,2019-09-01,2.884870,1198.0,-09-01,2017,9,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
2,1001_2019-10-01,1001,Autauga County,Alabama,2019-10-01,3.055843,1269.0,-10-01,2017,10,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
3,1001_2019-11-01,1001,Autauga County,Alabama,2019-11-01,2.993233,1243.0,-11-01,2017,11,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
4,1001_2019-12-01,1001,Autauga County,Alabama,2019-12-01,2.993233,1243.0,-12-01,2017,12,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101666,48175_2022-04-01,48175,Goliad County,Texas,2022-04-01,1.691226,101.0,-04-01,2020,4,...,2.0,2.0,1.1,1.2,1.9,56737,60492.0,60690,50000.0,52335.0
101667,48175_2022-05-01,48175,Goliad County,Texas,2022-05-01,1.674481,100.0,-05-01,2020,5,...,2.0,2.0,1.1,1.2,1.9,56737,60492.0,60690,50000.0,52335.0
101668,48175_2022-06-01,48175,Goliad County,Texas,2022-06-01,1.657736,99.0,-06-01,2020,6,...,2.0,2.0,1.1,1.2,1.9,56737,60492.0,60690,50000.0,52335.0
101669,48175_2022-07-01,48175,Goliad County,Texas,2022-07-01,1.657736,99.0,-07-01,2020,7,...,2.0,2.0,1.1,1.2,1.9,56737,60492.0,60690,50000.0,52335.0
101670,48175_2022-08-01,48175,Goliad County,Texas,2022-08-01,1.674481,100.0,-08-01,2020,8,...,2.0,2.0,1.1,1.2,1.9,56737,60492.0,60690,50000.0,52335.0

In [26]:
train_df = train_df.drop(["first_day_of_month", "Day Month", "county", "state"], axis = 'columns')

In [27]:
train_df

,row_id,cfips,microbusiness_density,active,Year,Month,pct_bb_2017_x,pct_bb_2018_x,pct_bb_2019_x,pct_bb_2020_x,...,pct_it_workers_2017_y,pct_it_workers_2018_y,pct_it_workers_2019_y,pct_it_workers_2020_y,pct_it_workers_2021_y,median_hh_inc_2017_y,median_hh_inc_2018_y,median_hh_inc_2019_y,median_hh_inc_2020_y,median_hh_inc_2021_y
0,1001_2019-08-01,1001,3.007682,1249.0,2017,8,76.6,78.9,80.6,82.7,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
1,1001_2019-09-01,1001,2.884870,1198.0,2017,9,76.6,78.9,80.6,82.7,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
2,1001_2019-10-01,1001,3.055843,1269.0,2017,10,76.6,78.9,80.6,82.7,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
3,1001_2019-11-01,1001,2.993233,1243.0,2017,11,76.6,78.9,80.6,82.7,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
4,1001_2019-12-01,1001,2.993233,1243.0,2017,12,76.6,78.9,80.6,82.7,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101666,48175_2022-04-01,48175,1.691226,101.0,2020,4,61.3,62.3,67.0,67.7,...,2.0,2.0,1.1,1.2,1.9,56737,60492.0,60690,50000.0,52335.0
101667,48175_2022-05-01,48175,1.674481,100.0,2020,5,61.3,62.3,67.0,67.7,...,2.0,2.0,1.1,1.2,1.9,56737,60492.0,60690,50000.0,52335.0
101668,48175_2022-06-01,48175,1.657736,99.0,2020,6,61.3,62.3,67.0,67.7,...,2.0,2.0,1.1,1.2,1.9,56737,60492.0,60690,50000.0,52335.0
101669,48175_2022-07-01,48175,1.657736,99.0,2020,7,61.3,62.3,67.0,67.7,...,2.0,2.0,1.1,1.2,1.9,56737,60492.0,60690,50000.0,52335.0
101670,48175_2022-08-01,48175,1.674481,100.0,2020,8,61.3,62.3,67.0,67.7,...,2.0,2.0,1.1,1.2,1.9,56737,60492.0,60690,50000.0,52335.0

In [22]:
train_df.to_csv('file.csv')
from google.colab import files
files.download('file.csv')